export const METERS_TBL = 'meters';
export const DAILY = 'Daily';

export const METERS_TBL_COLUMNS = {
    usc_number: 'usc_number',
    meter_serial_number:'meter_serial_number',
    dt_id: 'dt_id',
    feeder_id: 'feeder_id',
    consumer_type_id: 'consumer_type_id',
    utility_id:'utility_id',
    zone_id:'zone_id',
    circle_id: 'circle_id',
    sub_division_id: 'sub_division_id',
    sub_station_id: 'sub_station_id',
    first_name: 'first_name',
    laste_name: 'laste_name',
    address: 'address',
    phone1: 'phone1',
    emailid: 'emailid',
    old_meterid: 'old_meterid',
    old_meter_reading: 'old_meter_reading',
    date_disconnected_old_meter: 'date_disconnected_old_meter',
    phon2: 'phon2',
    email_verification_status: 'email_verification_status',
    phone_verification_status: 'phone_verification_status',
    latitude: 'latitude',
    longitude: 'longitude',
    saction_load: 'saction_load',
    conneced_load: 'conneced_load',
    contract_demand: 'contract_demand',
    supply_voltage: 'supply_voltage',
    service_status: 'service_status',
    tod: 'tod',
    tou: 'tou',
    bill_period: 'bill_period',
    mf: 'mf',
    consumer_phase_id: 'consumer_phase_id',
    third_party_feeder_code: 'third_party_feeder_code',
    third_party_dt_code: 'third_party_dt_code',
    polenumber: 'polenumber',
    created_by: 'created_by',
    created_date: 'created_date',
    updated_by: 'updated_by',
}